<a href="https://colab.research.google.com/github/evindag/Data-Visualization/blob/main/numpyintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a * b

array([ 2,  6, 12, 20])

In [ ]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [ ]:
np.random.randint(0,10,size=10)

array([6, 0, 1, 5, 9, 8, 1, 2, 4, 3])

In [ ]:
np.random.randint(0,10,size=10).reshape(3,3)

In [ ]:
 ar = np.random.randint(1,10,size=9)
 ar.reshape(3, 3)

In [ ]:
x = np.array([1,0,3,4])
x[3]=2.9
x

array([1, 0, 3, 2])