<a href="https://colab.research.google.com/github/evindag/Data-Visualization/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v = np.arange(0,30,3)

In [3]:
v[1]

3

In [4]:
catch = [1,2,3] # Fancy index
v[catch]

array([3, 6, 9])

In [5]:
v < 3   # true - false

array([ True, False, False, False, False, False, False, False, False,
       False])

In [7]:
v[v > 3] # condition

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
# Math
v / 5

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [10]:
v * 5 / 10

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

In [11]:
v ** 2

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729])

In [12]:
v - 1

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [13]:
np.subtract(v,1)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [14]:
np.add(v ,1)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [15]:
np.mean(v)

13.5

In [16]:
np.sum(v)

135

In [17]:
np.min(v)

0

In [18]:
np.max(v)

27

In [19]:
np.var(v)

74.25

In [20]:
#equation
# 5x + y = 12
# x + 3y = 10

a = np.array([[5,1],(1,3)])
b = np.array([12,10])
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])